//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for StatementStatus.
const (
	Blocked    StatementStatus = "Blocked"
	Done       StatementStatus = "Done"
	InProgress StatementStatus = "InProgress"
	Toxic      StatementStatus = "Toxic"
)

// Valid indicates whether the value is a known member of the StatementStatus enum.
func (e StatementStatus) Valid() bool {
	switch e {
	case Blocked:
		return true
	case Done:
		return true
	case InProgress:
		return true
	case Toxic:
		return true
	default:
		return false
	}
}

// Official defines model for Official.
type Official struct {
	Bio      *string `json:"bio,omitempty"`
	Contacts *struct {
		Official *[]struct {
			Type  *string `json:"type,omitempty"`
			Value *string `json:"value,omitempty"`
		} `json:"official,omitempty"`
		Social *[]struct {
			Handle   *string `json:"handle,omitempty"`
			Platform *string `json:"platform,omitempty"`
			Url      *string `json:"url,omitempty"`
		} `json:"social,omitempty"`
	} `json:"contacts,omitempty"`
	CurrentRole       *string   `json:"current_role,omitempty"`
	DoneTasks         *int      `json:"done_tasks,omitempty"`
	Flag              *bool     `json:"flag,omitempty"`
	FlagReason        *string   `json:"flag_reason,omitempty"`
	Handle            *string   `json:"handle,omitempty"`
	Id                string    `json:"id"`
	Name              string    `json:"name"`
	Party             *string   `json:"party,omitempty"`
	PastRoles         *[]string `json:"past_roles,omitempty"`
	PhotoUrl          *string   `json:"photo_url,omitempty"`
	Position          *string   `json:"position,omitempty"`
	TotalTasks        *int      `json:"total_tasks,omitempty"`
	VerificationScore *float32  `json:"verification_score,omitempty"`
}

// Statement defines model for Statement.
type Statement struct {
	BacklogPriority *int       `json:"backlog_priority,omitempty"`
	Content         *string    `json:"content,omitempty"`
	Date            *time.Time `json:"date,omitempty"`
	ExtractedBy     *string    `json:"extracted_by,omitempty"`
	Id              string     `json:"id"`
	OfficialId      string     `json:"official_id"`
	Sentiment       *string    `json:"sentiment,omitempty"`
	Source          *struct {
		Date        *time.Time `json:"date,omitempty"`
		MediaOutlet *string    `json:"media_outlet,omitempty"`
		Title       *string    `json:"title,omitempty"`
		Type        *string    `json:"type,omitempty"`
		Url         *string    `json:"url,omitempty"`
	} `json:"source,omitempty"`
	SourceUrl *string         `json:"source_url,omitempty"`
	Status    StatementStatus `json:"status"`
	Text      *string         `json:"text,omitempty"`
	Topics    *[]string       `json:"topics,omitempty"`
}

// StatementStatus defines model for Statement.Status.
type StatementStatus string

// ListStatementsParams defines parameters for ListStatements.
type ListStatementsParams struct {
	OfficialId *string `form:"official_id,omitempty" json:"official_id,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/v1/officials)
	ListOfficials(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/statements)
	ListStatements(w http.ResponseWriter, r *http.Request, params ListStatementsParams)

	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListOfficials operation middleware
func (siw *ServerInterfaceWrapper) ListOfficials(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOfficials(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListStatements operation middleware
func (siw *ServerInterfaceWrapper) ListStatements(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListStatementsParams

	// ------------- Optional query parameter "official_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "official_id", r.URL.Query(), &params.OfficialId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "official_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "official_id", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListStatements(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/officials", wrapper.ListOfficials)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/statements", wrapper.ListStatements)

	return m
}
